name: ExploraConnect
favicon: null
layout_spectrum: 0.3369042039848864
typography_spectrum: 0.9562569952104241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8165348845068365
  lightness: 0.5900996301788837
  saturation: 0.26429169275797904
  rhythmicContrast: 0.9345587922725827
purpose: []
